# Generated by Django 5.0.6 on 2024-07-03 15:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='type',
            field=models.CharField(choices=[('particular', 'Particular'), ('enterprise', 'Enterprise'), ('staff', 'Staff')], default='Particular', max_length=50),
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('availability', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Driver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
