# Generated by Django 5.0.6 on 2024-07-03 15:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='users',
        ),
        migrations.AlterField(
            model_name='discount',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='UserDiscount',
        ),
    ]
